apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-namespace
  labels:
    app: nginx
spec:
  replicas: 2                              # Initial Replica count set to 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: redninja009/nginx-minimal:V-04     # Custom Nginx image use kiya
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: my-namespace
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80                             # Service port
      targetPort: 80                       # Nginx pod container port
      nodePort: 30007                      # NodePort (30000-32767 range)
