apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80            # Pod ke andar ka port (Nginx ka HTTP port)
      targetPort: 80       # Pod ka container port jahan traffic forward hoga
      nodePort: 30007      # NodePort jo cluster ke bahar se access hoga (range: 30000-32767)
