---
apiVersion: v1
kind: Service
metadata:
  name:  nginx-phpfpm 
spec:
  type: NodePort
  selector:
     app:  nginx-phpfpm
  ports:
    - port: 8092  
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
      targetPort: 8092 
       # Optional field  By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30012
